### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Lone1106** [Lone1106/flashcard-app#1]
- [ ] delete all cards of a User function
- [ ] put userObj into context instead of passing it to every component separately
- [ ] use lazy loading on unused components
- [ ] replace Reauth password placeholder
- [ ] redo route restrictions
